<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerARlNzlF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerARlNzlF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerARlNzlF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerARlNzlF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerARlNzlF\App_KernelDevDebugContainer([
    'container.build_hash' => 'ARlNzlF',
    'container.build_id' => '03bb04a5',
    'container.build_time' => 1603956932,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerARlNzlF');
